BEGIN
	WITH SRD AS (
		SELECT 
	  DISTINCT SRD.RD_FILIAL
			  ,SRD.RD_CC
			  ,SRD.RD_PD
		FROM SRD990 AS SRD WHERE SRD.D_E_L_E_T_=' '
	)    
  SELECT t.* INTO !TABLENAME!
  FROM (
        SELECT 
     DISTINCT CTT.CTT_FILIAL 
             ,CTT.CTT_CUSTO
             ,CTT.CTT_DESC01 
         FROM CTT990 CTT
         JOIN SRD ON (CTT.CTT_CUSTO=SRD.RD_CC AND CTT.CTT_FILIAL=(CASE CTT.CTT_FILIAL WHEN ' ' THEN ' ' ELSE SRD.RD_FILIAL END))
         JOIN SRV990 SRV ON (SRD.RD_PD=SRV.RV_COD AND ((CASE SRV.RV_FILIAL WHEN '' THEN 1 WHEN SRD.RD_FILIAL THEN 1 ELSE 0 END)=1) )	  
         JOIN ZY_990 ZY_ ON (ZY_.ZY__CODIGO=SRV.RV_ZY__COD AND ((CASE ZY_.ZY__FILIAL WHEN '' THEN 1 WHEN SRV.RV_FILIAL THEN 1 ELSE 0 END)=1) )	  
        WHERE CTT.D_E_L_E_T_=''
          AND SRV.D_E_L_E_T_=''
          AND ZY_.D_E_L_E_T_=''      
          AND CTT.CTT_FILIAL=(CASE CTT.CTT_FILIAL WHEN ' ' THEN ' ' ELSE SRD.RD_FILIAL END)
          AND SRV.RV_FILIAL=(CASE SRV.RV_FILIAL WHEN ' ' THEN ' ' ELSE SRD.RD_FILIAL END)
          AND ZY_.ZY__FILIAL=(CASE ZY_.ZY__FILIAL WHEN ' ' THEN ' ' ELSE SRD.RD_FILIAL END)
 ) t
END

