SELECT 
DISTINCT SQB.QB_FILIAL
        ,SQB.QB_DEPTO
        ,SQB.QB_DESCRIC
    FROM SQB990 SQB
    JOIN SRA990 SRA ON (SQB.QB_DEPTO=SRA.RA_DEPTO)
   WHERE SQB.D_E_L_E_T_=''
     AND SRA.D_E_L_E_T_=''
     AND SQB.QB_DEPTO=SRA.RA_DEPTO
     AND SQB.QB_FILIAL=(CASE SQB.QB_FILIAL WHEN '' THEN '' ELSE LEFT(SRA.RA_FILIAL,LEN(SQB.QB_FILIAL)) END)