SELECT 
DISTINCT  SRJ.RJ_FILIAL
         ,SRJ.RJ_FUNCAO
         ,SRJ.RJ_DESC
     FROM SRJ990 SRJ     JOIN SRA990 SRA ON (SRJ.RJ_FUNCAO=SRA.RA_CODFUNC AND ((CASE SRJ.RJ_FILIAL WHEN '' THEN 1 WHEN SRA.RA_FILIAL THEN 1 ELSE 0 END)=1) )
    WHERE SRJ.D_E_L_E_T_=''
      AND SRA.D_E_L_E_T_=''
      AND (SRJ.RJ_FUNCAO=SRA.RA_CODFUNC AND ((CASE SRJ.RJ_FILIAL WHEN '' THEN 1 WHEN SRA.RA_FILIAL THEN 1 ELSE 0 END)=1) )