SELECT 
 DISTINCT ZY_.ZY__FILIAL
         ,ZY_.ZY__CODIGO
         ,ZY_.ZY__SQLFLD
         ,ZY_.ZY__DESC
		 ,RTRIM(LTRIM(CONVERT(VARCHAR(1024),ZY_.ZY__HTML))) ZY__HTML
FROM ZY_990 ZY_ 
  JOIN ( 
   SELECT 
 DISTINCT ZY_.ZY__FILIAL
         ,ZY_.ZY__MASTER
     FROM ZY_990 ZY_
     JOIN SRV990 SRV ON (ZY_.ZY__CODIGO=SRV.RV_ZY__COD AND ((CASE ZY_.ZY__FILIAL WHEN '' THEN 1 WHEN SRV.RV_FILIAL THEN 1 ELSE 0 END)=1) )     
     JOIN SRD990 SRD ON (SRV.RV_COD=SRD.RD_PD AND ((CASE ZY_.ZY__FILIAL WHEN '' THEN 1 WHEN SRD.RD_FILIAL THEN 1 ELSE 0 END)=1) )
    WHERE ZY_.D_E_L_E_T_=''
      AND SRV.D_E_L_E_T_=''
      AND SRD.D_E_L_E_T_=''
      AND ZY_.ZY__FILIAL=(CASE ZY_.ZY__FILIAL WHEN '' THEN '' ELSE SRV.RV_FILIAL END)
      AND SRV.RV_FILIAL=(CASE SRV.RV_FILIAL WHEN '' THEN '' ELSE SRD.RD_FILIAL END)
   ) t
    ON ( ZY_.ZY__FILIAL=t.ZY__FILIAL AND ZY_.ZY__CODIGO=t.ZY__MASTER)
WHERE ZY_.D_E_L_E_T_=''