BEGIN
  SET LANGUAGE PORTUGUESE
  SELECT t.* INTO !TABLENAME!
  FROM (
      SELECT 
    DISTINCT SRD.RD_DATARQ
            ,RIGHT(SRD.RD_DATARQ,2)+'/'+LEFT(SRD.RD_DATARQ,4) RD_MESANO
            ,LEFT(SRD.RD_DATARQ,4)+'/'+RIGHT(SRD.RD_DATARQ,2) RD_ANOMES
            ,CONCAT(UPPER(LEFT(DATENAME(MONTH,CAST(CONCAT(SRD.RD_DATARQ,'01') AS DATETIME)),3)),LEFT(SRD.RD_DATARQ,4)) ALIASACM
         FROM SRD990 SRD
        WHERE SRD.D_E_L_E_T_=''
          AND SRD.RD_DATARQ BETWEEN !DATARQDE! AND !DATARQATE!
     GROUP BY SRD.RD_DATARQ 
 ) t
END