SELECT
		  SRD.RD_FILIAL
		 ,SRD.RD_DATARQ
		 ,SRD.RD_CC
		 ,CTT.CTT_DESC01
		 ,ZY_.ZY__CODIGO
		 ,ZY_.ZY__DESC
		 ,RTRIM(LTRIM(CONVERT(VARCHAR(1024),ZY_.ZY__HTML))) ZY__HTML
		 ,SRJ.RJ_FUNCAO
		 ,SRJ.RJ_DESC
		 ,SUM(SRD.RD_VALOR) RD_VALOR
     FROM CTT990 CTT
     JOIN SRD990 SRD ON (CTT.CTT_CUSTO=SRD.RD_CC)
	 JOIN SRV990 SRV ON (SRD.RD_PD=SRV.RV_COD)
	 JOIN ZY_990 ZY_ ON (ZY_.ZY__CODIGO=SRV.RV_ZY__COD)
     JOIN SRA990 SRA ON (SRA.RA_FILIAL=SRD.RD_FILIAL AND SRA.RA_MAT=SRD.RD_MAT )
	 JOIN SRJ990 SRJ ON (SRA.RA_CODFUNC=SRJ.RJ_FUNCAO)
	WHERE CTT.D_E_L_E_T_=''
      AND SRD.D_E_L_E_T_=''
	  AND SRV.D_E_L_E_T_=''
	  AND ZY_.D_E_L_E_T_=''
	  AND SRA.D_E_L_E_T_=''
	  AND SRJ.D_E_L_E_T_=''
      AND CTT.CTT_FILIAL=(CASE CTT.CTT_FILIAL WHEN '' THEN '' ELSE LEFT(SRD.RD_FILIAL,LEN(CTT.CTT_FILIAL)) END)
	  AND SRV.RV_FILIAL=(CASE SRV.RV_FILIAL WHEN '' THEN '' ELSE LEFT(SRD.RD_FILIAL,LEN(SRV.RV_FILIAL)) END)
	  AND ZY_.ZY__FILIAL=(CASE ZY_.ZY__FILIAL WHEN '' THEN '' ELSE LEFT(SRD.RD_FILIAL,LEN(ZY_.ZY__FILIAL)) END)
	  AND SRJ.RJ_FILIAL=(CASE SRJ.RJ_FILIAL WHEN '' THEN '' ELSE LEFT(SRA.RA_FILIAL,LEN(ZY_.ZY__FILIAL)) END)
      AND SRD.RD_DATARQ BETWEEN !DATARQDE! AND !DATARQATE!
      AND SRD.RD_CC BETWEEN !CCDE! AND !CCATE!
      AND SRA.RA_FILIAL BETWEEN !FILIALDE! AND !FILIALATE!
      AND SRD.RD_FILIAL BETWEEN !FILIALDE! AND !FILIALATE!
      AND ZY_.ZY__CODIGO BETWEEN !GRUPODE! AND !GRUPOATE!
      AND SRJ.RJ_FUNCAO BETWEEN !FUNCAODE! AND !FUNCAOATE!
GROUP BY SRD.RD_FILIAL
		 ,SRD.RD_DATARQ
		 ,SRD.RD_CC
		 ,CTT.CTT_DESC01
		 ,ZY_.ZY__CODIGO
		 ,ZY_.ZY__DESC
		 ,RTRIM(LTRIM(CONVERT(VARCHAR(1024),ZY_.ZY__HTML)))
		 ,SRJ.RJ_FUNCAO
		 ,SRJ.RJ_DESC