SELECT 
		  SRD.RD_FILIAL
		 ,SRD.RD_DATARQ
		 ,SRD.RD_CC
		 ,CTT.CTT_DESC01
		 ,ZY_.ZY__CODIGO
		 ,ZY_.ZY__DESC
		 ,RTRIM(LTRIM(CONVERT(VARCHAR(1024),ZY_.ZY__HTML))) ZY__HTML
		 ,SRJ.RJ_FUNCAO
		 ,SRJ.RJ_DESC
		 ,SUM(SRD.RD_VALOR) RD_VALOR 
     FROM CTT990 CTT
     JOIN SRD990 SRD ON (CTT.CTT_CUSTO=SRD.RD_CC)
	 JOIN SRV990 SRV ON (SRD.RD_PD=SRV.RV_COD AND ((CASE SRV.RV_FILIAL WHEN '' THEN 1 WHEN SRD.RD_FILIAL THEN 1 ELSE 0 END)=1) )	  
	 JOIN ZY_990 ZY_ ON (ZY_.ZY__CODIGO=SRV.RV_ZY__COD AND ((CASE ZY_.ZY__FILIAL WHEN '' THEN 1 WHEN SRV.RV_FILIAL THEN 1 ELSE 0 END)=1) )	  
     JOIN SRA990 SRA ON (SRA.RA_FILIAL=SRD.RD_FILIAL AND SRA.RA_MAT=SRD.RD_MAT )
	 JOIN SRJ990 SRJ ON (SRA.RA_CODFUNC=SRJ.RJ_FUNCAO AND ((CASE SRJ.RJ_FILIAL WHEN '' THEN 1 WHEN SRA.RA_FILIAL THEN 1 ELSE 0 END)=1) )	  	  
	WHERE CTT.D_E_L_E_T_=''
      AND SRD.D_E_L_E_T_=''
	  AND SRV.D_E_L_E_T_=''
	  AND ZY_.D_E_L_E_T_='' 
	  AND SRA.D_E_L_E_T_=''  
	  AND SRJ.D_E_L_E_T_=''   
      AND CTT.CTT_FILIAL=(CASE CTT.CTT_FILIAL WHEN '' THEN '' ELSE SRD.RD_FILIAL END)
	  AND SRV.RV_FILIAL=(CASE SRV.RV_FILIAL WHEN '' THEN '' ELSE SRD.RD_FILIAL END)
	  AND ZY_.ZY__FILIAL=(CASE ZY_.ZY__FILIAL WHEN '' THEN '' ELSE SRD.RD_FILIAL END)
	  AND SRJ.RJ_FILIAL=(CASE SRJ.RJ_FILIAL WHEN '' THEN '' ELSE SRA.RA_FILIAL END)
      AND SRD.RD_DATARQ BETWEEN !DATARQDE! AND !DATARQATE!
      AND SRD.RD_CC BETWEEN !CCDE! AND !CCATE!
      AND SRD.RD_FILIAL BETWEEN !FILIALDE! AND !FILIALATE!
      AND ZY_.ZY__CODIGO BETWEEN !GRUPODE! AND !GRUPOATE!
      AND SRJ.RJ_FUNCAO BETWEEN !FUNCAODE! AND !FUNCAOATE!
GROUP BY SRD.RD_FILIAL
		 ,SRD.RD_DATARQ
		 ,SRD.RD_CC
		 ,CTT.CTT_DESC01
		 ,ZY_.ZY__CODIGO
		 ,ZY_.ZY__DESC
		 ,RTRIM(LTRIM(CONVERT(VARCHAR(1024),ZY_.ZY__HTML)))
		 ,SRJ.RJ_FUNCAO
		 ,SRJ.RJ_DESC



