SELECT RA_FILIAL
      ,RD_DATARQ
      ,RD_CC
      ,CTT_DESC01
      ,ZY__MASTER
      ,ZY__CODIGO
      ,ZY__DESC
	  ,ZY__HTML
      ,RV_COD
      ,RV_DESC
      ,RJ_FUNCAO
      ,RJ_DESC
      ,RD_VALOR
 FROM v99GRPVERBASFUNCAO
WHERE RD_DATARQ BETWEEN !DATARQDE! AND !DATARQATE!
  AND RD_CC BETWEEN !CCDE! AND !CCATE!
  AND RA_FILIAL BETWEEN !FILIALDE! AND !FILIALATE!
  AND ZY__CODIGO BETWEEN !GRUPODE! AND !GRUPOATE!
  AND RJ_FUNCAO BETWEEN !FUNCAODE! AND !FUNCAOATE!
  AND RV_COD BETWEEN !VERBADE! AND !VERBAATE!