SELECT 
DISTINCT SR6.R6_FILIAL
         ,SR6.R6_TURNO
         ,SR6.R6_DESC
     FROM SR6990 SR6
	 JOIN SRA990 SRA ON (SR6.R6_TURNO=SRA.RA_DEPTO AND ((CASE SR6.R6_FILIAL WHEN '' THEN 1 WHEN SRA.RA_FILIAL THEN 1 ELSE 0 END)=1) )
    WHERE SR6.D_E_L_E_T_=''
      AND SRA.D_E_L_E_T_=''
      AND (SR6.R6_TURNO=SRA.RA_DEPTO AND ((CASE SR6.R6_FILIAL WHEN '' THEN 1 WHEN SRA.RA_FILIAL THEN 1 ELSE 0 END)=1) )