SELECT 
DISTINCT SR6.R6_FILIAL
        ,SR6.R6_TURNO
        ,SR6.R6_DESC
    FROM SR6990 SR6
    JOIN SRA990 SRA ON (SR6.R6_TURNO=SRA.RA_TNOTRAB)
   WHERE SR6.D_E_L_E_T_=''
     AND SRA.D_E_L_E_T_=''
     AND SR6.R6_TURNO=SRA.RA_TNOTRAB
     AND SR6.R6_FILIAL=(CASE SR6.R6_FILIAL WHEN '' THEN '' ELSE LEFT(SRA.RA_FILIAL,LEN(SR6.R6_FILIAL)) END)